data = [1,2,3,4,5]
print("現在のデータは",data,"です。")
print("data[::-1]をfor文で処理します。")
for d in data[::-1]:
    print(d)
print("data[::-1]は",data[::-1],"です。")
print("現在のデータは",data,"です。")
print("reversed(data)をfor文で処理します。")
for d in  reversed(data):
    print(d)
print("reversed(data)は",reversed(data),"です。")
print("現在のデータは",data,"です。")
print("data.reversed()を処理します。")
data.reverse()
print("現在のデータは",data,"です。")
print("データを戻します。")
data.reverse()
print("現在のデータは",data,"です。")

print("dataをイテレータで表示します。")
it = iter(data)
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))

print("reversed(data)をイテレータで表示します。")
rv = reversed(data)
print(next(rv))
print(next(rv))
print(next(rv))
print(next(rv))
print(next(rv))